In [79]:
import pandas as pd
import locale
locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')

'pt_BR.UTF-8'

In [80]:
file = "BetHistory16a23-12-2024.csv"

In [103]:
def nomarliza_coluna_lp(value: str) -> float:
    "Coverte a coluna L/P de string para float"
    if '(' in value:
        value = value.replace('(','').replace(')', '')
        return -float(value)
    return float(value)

def prepara_dados_btts(file_path: str) -> None:
    df = pd.read_csv(file_path)
    df['Mercado'] = df['Mercado'].astype(str)
    df['Seleção'] = df['Seleção'].astype(str)
    colunas = ['Mercado', 'Seleção', 'Aposta realizada', 'Aposta ($)', 'Média de probabilidades correspondidas', 'Lucro/Prejuízo ($)']
    df_aux = df[colunas]
    df_btts = df_aux[df_aux['Seleção'] == 'Sim']
    df_btts = df_btts.rename(columns={
        'Aposta realizada': 'Data',
        'Aposta ($)': 'Stake',
        'Média de probabilidades correspondidas': 'Odd',
        'Lucro/Prejuízo ($)': 'L/P',
    })
    df_btts['L/P'] = df_btts['L/P'].apply(nomarliza_coluna_lp)
    df_btts['Data'] = pd.to_datetime(df_btts['Data'], format='%d-%b-%y %H:%M')
    df_btts['Data'] = df_btts['Data'].dt.date
    return df_btts

In [104]:
btts = prepara_dados_btts(file)

In [105]:
btts.head()

,Mercado,Seleção,Data,Stake,Odd,L/P
0,Futebol / Campinense x Afogados Ingazeira / Am...,Sim,2024-12-23,3.5,1.67,-3.50
2,Futebol / Jong Ajax Amsterdam x Roda JC / Ambo...,Sim,2024-12-23,3.5,1.50,1.76
3,Futebol / Hatayspor x Adana Demirspor / Ambos ...,Sim,2024-12-23,3.5,1.79,2.77
4,Futebol / Hyderabad FC x Northeast United / Am...,Sim,2024-12-23,3.5,1.67,2.35
5,Futebol / Colchester United U21 x Bristol City...,Sim,2024-12-23,3.5,1.44,1.54

In [102]:
btts.describe()

            Stake         Odd         L/P
count  155.000000  155.000000  155.000000
mean     1.619226    1.629806    1.194129
std      0.619107    0.141405    0.552535
min      1.000000    1.120000    0.120000
25%      1.000000    1.560000    0.795000
50%      2.000000    1.640000    1.000000
75%      2.000000    1.720000    1.460000
max      3.500000    2.000000    3.500000